# Generated by Django 4.0.6 on 2022-07-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_speciality_alter_city_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('company', models.CharField(max_length=250, verbose_name='Company name')),
                ('description', models.TextField(verbose_name='Description')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.city', verbose_name='City')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.speciality')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacansies',
            },
        ),
    ]
